humanoid-path-planner/hpp-constraints

include/hpp/constraints/impl/hybrid-solver.hh
This commit ensures users that two configurations computed to lie in the same
leaf of the foliation relative to a numerical constraint are effectively
considered as such by the manipulation steering method.
If q1 and q2 and q3 are such that
||f(q1) - f (q3) || < eps,
||f(q2) - f (q3) || < eps,
|| f(q2) - f (q1)|| may be bigger than eps and therefore considered as not
lying on the same leaf.
=> When solving an equation, iterate until error is below half threshold.

src/matrix-view.cc
- if a is empty, set a to b witout iterating into b,
- add an assert.
This pull request fixes a segmentation fault in method
void BlockIndex::add (segments_t& a, const segments_t& b)
when a is empty and b contains 2 segments.
=> Fix methods BlockIndex::add

include/hpp/constraints/affine-function.hh, include/hpp/constraints/explicit-solver.hh, include/hpp/constraints/impl/hybrid-solver.hh, include/hpp/constraints/impl/iterative-solver.hh, include/hpp/constraints/iterative-solver.hh, include/hpp/constraints/matrix-view.hh, src/explicit-solver.cc, src/generic-transformation.cc, src/hybrid-solver.cc, src/iterative-solver.cc, tests/explicit-solver.cc, tests/generic-transformation.cc, tests/hybrid-solver.cc, tests/iterative-solver.cc, tests/matrix-view.cc, tests/util.hh
- ExplicitSolver:
- use `g(q_{out}) = f(q_{in}) + rhs` instead of `q_{out} = f(q_{in}) + rhs`,
- (bugfix) use derivative of addition operation.
- IterativeSolver:
- update computation of saturation,
- MatrixBlock:
- optimization
=> Improvments and bug fixes in solvers

NEWS, include/hpp/constraints/active-set-differentiable-function.hh, include/hpp/constraints/explicit-constraint-set.hh, include/hpp/constraints/explicit.hh, include/hpp/constraints/explicit/function.hh, include/hpp/constraints/fwd.hh, include/hpp/constraints/impl/matrix-view-operation.hh, include/hpp/constraints/solver/by-substitution.hh, include/hpp/constraints/solver/hierarchical-iterative.hh, include/hpp/constraints/solver/impl/hierarchical-iterative.hh, include/hpp/constraints/symbolic-function.hh, src/explicit-constraint-set.cc, src/explicit.cc, src/explicit/function.cc, src/locked-joint.cc, src/solver/by-substitution.cc, src/solver/hierarchical-iterative.cc, tests/explicit-constraint-set.cc, tests/solver-by-substitution.cc, tests/solver-hierarchical-iterative.cc, tests/util.hh
* Refactor ExplicitConstraintSet: rename members and methods to better fit RSS
paper notation and pinocchio convention:
- argSize -> nq,
- derSize -> nv,
- freeArgs -> notOutArgs_,
- freeDers -> notOutDers_,
- viewJacobian -> jacobianNotOutToOut.
* Constructor and create methods of Explicit take a LiegroupSpace instead of a
robot,
* Modify prototype of BySubstitution::projectVectorOnKernel
- vectorIn_t -> ConfigurationIn_t,
- vectorOut_t -> ConfigurationOut_t.
* In class HierarchicalIterative, rename "reduction" -> "free variables".
=> Refactoring

src/explicit/relative-pose.cc, tests/solver-by-substitution.cc
- add an assert in explicit_::RelativePose to check that configuration
space of second joint is SE3 or R3xSO3,
- it test solver-by-substitution, apply explicit constraint on root joint.
=> [RelativePose] Fix test solver-by-substitution

NEWS, include/hpp/constraints/explicit-constraint-set.hh, include/hpp/constraints/implicit.hh, include/hpp/constraints/locked-joint.hh, include/hpp/constraints/solver/hierarchical-iterative.hh, src/explicit-constraint-set.cc, src/implicit.cc, src/locked-joint.cc, src/solver/hierarchical-iterative.cc, tests/solver-by-substitution.cc
Implicit class does not store value Jacobian and rightHandSide anymore
Setters and getters to right hand side handle vector of size the output of the function whatever the
comparison types are. Some asserts have been added to check that 0 are passed for non Equality comparisons.
=> Refactor right hand side handling in constraints and solvers

NEWS, include/hpp/constraints/implicit.hh, include/hpp/constraints/locked-joint.hh, src/implicit.cc, src/locked-joint.cc, src/solver/hierarchical-iterative.cc
- methods setting and getting the right hand side are not deprecated anymore,
- deprecated methods have been remove
=> Clean up class Implicit

NEWS, doc/right-hand-side.tex, include/hpp/constraints/solver/hierarchical-iterative.hh, src/solver/hierarchical-iterative.cc, tests/solver-by-substitution.cc
Method HierarchicalIterative::definesSubmanifold test whether the solution manifold of a solver is a submanifold of the solution manifold of another solver.
Somes tests have been added in tests/solver-by-substitution.
=> [HierarchicalIterative] Add a method testing inclusion of manifolds

include/hpp/constraints/solver/by-substitution.hh
- as computed by isSatisfied method.
=> [BySubstitution] Add a method to get the dimension of the error

src/generic-transformation.cc, tests/convex-shape.cc, tests/multithread.cc, tests/symbolic-calculus.cc
FTR, I also had to add `-Wno-c++11-narrowing` for clang 8 or `-Wno-narrowing` for GCC 9
While here, fix usual issues with https://github.com/stack-of-tasks/pinocchio/issues/849
=> explicit cast template arguments, fix #90

tests/convex-shape.cc, tests/logarithm.cc, tests/multithread.cc, tests/symbolic-calculus.cc
ref https://github.com/stack-of-tasks/pinocchio/issues/849
This was already adressed in both #94 and #96, so the header was added
twice in some files, but one was still missing.
=> include pinocchio before boost

include/hpp/constraints/solver/impl/by-substitution.hh
Hi,
In the test of hpp-wholebody-step, at some point, on this line, and on my system (18.04), `qopt` is of size 0.
Considering the line 137: ` if (optimize && qopt.size() > 0) arg = qopt;`, I suggest to add this check, which fix the tests in my use case (without breaking the tests of hpp-constraints), but I actually have no idea what I'm doing :)
=> fix tests in hpp-wholebody-step

NEWS, doc/main-page.hh, include/hpp/constraints/differentiable-function.hh, include/hpp/constraints/explicit.hh, include/hpp/constraints/explicit/relative-pose.hh, src/explicit-constraint-set.cc, src/explicit/relative-pose.cc, src/implicit.cc, tests/explicit-constraint-set.cc
- Computation of right hand side was wrong, especially when the ExplicitConstraintSet included a
RelativePose with comparison type Equal at rank 3 (rotation around x).
- a test has been added.
- the new version has been successfully tested with benchmark romeo-placard and with a new
benchmark.
=> [ExplicitConstraintSet] Fix computation of right hand side

include/hpp/constraints/locked-joint.hh
Implicit formulation (function h) takes values in a vector space.
=> [Doc] Make documentation of LockedJoint more accurate.

CMakeLists.txt, include/hpp/constraints/comparison-types.hh, include/hpp/constraints/explicit/relative-pose.hh, include/hpp/constraints/fwd.hh, include/hpp/constraints/implicit-constraint-set.hh, include/hpp/constraints/implicit.hh, include/hpp/constraints/solver/by-substitution.hh, src/explicit-constraint-set.cc, src/explicit/convex-shape-contact.cc, src/explicit/relative-pose.cc, src/implicit.cc, src/locked-joint.cc, src/solver/by-substitution.cc, src/solver/hierarchical-iterative.cc, tests/CMakeLists.txt, tests/comparison-types.cc, tests/explicit-constraint-set.cc, tests/solver-by-substitution.cc, tests/solver-hierarchical-iterative.cc
- make comparison types required in constructors,
- provide operator<< to ease construction of ComparisonTypes_t.
=> Refactor Implicit initialization

NEWS, include/hpp/constraints/convex-shape-contact.hh, include/hpp/constraints/explicit-constraint-set.hh, include/hpp/constraints/explicit.hh, include/hpp/constraints/explicit/convex-shape-contact.hh, include/hpp/constraints/explicit/relative-pose.hh, include/hpp/constraints/fwd.hh, include/hpp/constraints/generic-transformation.hh, include/hpp/constraints/implicit-constraint-set.hh, include/hpp/constraints/implicit.hh, include/hpp/constraints/matrix-view.hh, include/hpp/constraints/solver/by-substitution.hh, include/hpp/constraints/solver/hierarchical-iterative.hh, include/hpp/constraints/solver/impl/by-substitution.hh, src/convex-shape-contact.cc, src/explicit-constraint-set.cc, src/explicit.cc, src/explicit/convex-shape-contact.cc, src/explicit/relative-pose.cc, src/generic-transformation.cc, src/implicit.cc, src/locked-joint.cc, src/solver/by-substitution.cc, src/solver/hierarchical-iterative.cc, tests/convex-shape-contact.cc, tests/explicit-constraint-set.cc, tests/generic-transformation.cc, tests/solver-by-substitution.cc, tests/solver-hierarchical-iterative.cc, tests/test-jacobians.cc
Solver now handle constraints in Lie groups.
typedef RelativeTransformationR3xSO3 compute the relative position between two frames as an element of R3xSO(3).
=> Constraints in Lie group

tests/CMakeLists.txt
Now that tests are always required in version 4.10.1, i got some linking issue with `librt.so` on some Linux platform that needs it. Here is a fix that worked for me. Hope it can help !
=> [CMake] Link to rt library in test

include/hpp/constraints/matrix-view.hh, src/explicit/convex-shape-contact.cc
- Use correct comparison types in explicit_::RelativePose instances stored in class ConvexShapeContactComplement.
- add operator= in MatrixView to suppress a compilation warning.
=> Fix ConvexShapeContactComplement

include/hpp/constraints/active-set-differentiable-function.hh, include/hpp/constraints/affine-function.hh, include/hpp/constraints/com-between-feet.hh, include/hpp/constraints/configuration-constraint.hh, include/hpp/constraints/convex-shape-contact.hh, include/hpp/constraints/convex-shape.hh, include/hpp/constraints/differentiable-function-set.hh, include/hpp/constraints/differentiable-function.hh, include/hpp/constraints/distance-between-bodies.hh, include/hpp/constraints/distance-between-points-in-bodies.hh, include/hpp/constraints/explicit.hh, include/hpp/constraints/explicit/implicit-function.hh, include/hpp/constraints/explicit/relative-transformation.hh, include/hpp/constraints/function/difference.hh, include/hpp/constraints/function/of-parameter-subset.hh, include/hpp/constraints/generic-transformation.hh, include/hpp/constraints/manipulability.hh, include/hpp/constraints/qp-static-stability.hh, include/hpp/constraints/relative-com.hh, include/hpp/constraints/solver/by-substitution.hh, include/hpp/constraints/static-stability.hh, include/hpp/constraints/symbolic-function.hh, src/explicit-constraint-set.cc, src/explicit.cc, src/explicit/convex-shape-contact.cc, src/implicit.cc, src/solver/by-substitution.cc, src/solver/hierarchical-iterative.cc, tests/generic-transformation.cc, tests/solver-hierarchical-iterative.cc
We sometimes need to compare DifferentiableFunctions in order to build lists without duplicates or easily detect incompatible constraints. So far we were using pointer equality or name equality. Now the fields are compared.
- Equality operator implemented in DifferentiableFunction and all child classes
- Equality tests like dfPtr1 == dfPtr2 replaced with *dfPtr1 == *dfPtr2 where relevant
=> Implement DifferentiableFunction equality to avoir comparing pointer

include/hpp/constraints/convex-shape.hh, include/hpp/constraints/qp-static-stability.hh
- ConvexShape::operator== return true if objects are equal,
- QPStaticStability::isEqual does not use private member of parent class
anymore.
=> [DifferentiableFunction] Fix operator==

include/hpp/constraints/convex-shape-contact.hh, include/hpp/constraints/differentiable-function.hh, include/hpp/constraints/matrix-view.hh, src/convex-shape-contact.cc, src/differentiable-function.cc
- Remove code inside `#ifndef NDEBUG` directives in headers,
- move some inline code into cc files.
=> Fix ConvexShapeContactComplement::isEqual method

include/hpp/constraints/explicit.hh, include/hpp/constraints/implicit.hh
Due to inconsitent use of space and tabs, as well as some typos,
the documentation for implicit constraint does not show up properly.
This has been fixed in this commit.
=> Fix documentation indentation for constraints

include/hpp/constraints/qp-static-stability.hh, include/hpp/constraints/static-stability.hh, src/explicit/convex-shape-contact.cc, src/qp-static-stability.cc, src/static-stability.cc
1. An explicit constraint was created formerly even when the robot contact surface was on a robot link and not on a freeflying object. This PR fixes this bug.
2. Refactor and document class QPStaticStability: some input parameters of the constructor were not used.
=> [ConvexShapeContact] Add a check before creating an explicit constraint

include/hpp/constraints/convex-shape-contact.hh, include/hpp/constraints/differentiable-function.hh, include/hpp/constraints/explicit/implicit-function.hh, include/hpp/constraints/explicit/relative-transformation.hh, include/hpp/constraints/fwd.hh, include/hpp/constraints/generic-transformation.hh, include/hpp/constraints/implicit.hh, include/hpp/constraints/locked-joint.hh, src/explicit/implicit-function.cc, src/implicit.cc, src/locked-joint.cc, tests/convex-shape-contact.cc, tests/generic-transformation.cc
Some function values are dependent on the pose of a pair of joints, such that the value of the function remains constant if the joints relative motion is constrained in a transition. 
One case where this is useful is when propagating constraints backwards: if we know that i) a goal configuration must satisfy constraint `c1`, and ii) `c1` function involves joints `j1` and `j2`, and iii) `j1` and `j2` are constrained in the transition leading to the goal configuration, we can conclude that the configuration right before the transition (and even along the transition) must satisfy the constraint.
=> Add method to retrieve joints involved in a constraint function

include/hpp/constraints/convex-shape-contact.hh, include/hpp/constraints/differentiable-function-set.hh, include/hpp/constraints/differentiable-function.hh, include/hpp/constraints/explicit/convex-shape-contact.hh, include/hpp/constraints/explicit/implicit-function.hh, include/hpp/constraints/explicit/relative-transformation.hh, include/hpp/constraints/fwd.hh, include/hpp/constraints/generic-transformation.hh, src/explicit/convex-shape-contact.cc, src/explicit/implicit-function.cc, src/generic-transformation.cc, src/generic-transformation/helper.hh, src/solver/by-substitution.cc, src/solver/hierarchical-iterative.cc, tests/convex-shape-contact.cc, tests/generic-transformation.cc
and also Use vector instead of lists in `JointAndShapes_t`.
=> [ConvexShapeContact] Fix bug in indexing of pairs of contact surfaces

src/explicit/implicit-function.cc, tests/generic-transformation.cc
Bug in API `dependsOnRelPoseBetween` when there is a locked joint with
more than 1 DOF. This happened due to a misunderstanding of
Eigen::MatrixBlocks::nbRows() method, which actually returns total
number of row indices, rather than the number of row index **intervals*.
This has been fixed and unit test is modified to detect this kind of
errors.
=> fix: detect locked joint with more than 1 DOF

include/hpp/constraints/differentiable-function-set.hh
The assert raises issue even when the calculation is performed properly,
because the assert checks even before `result` is fully
computed. This has been fixed by simply moving the assert line.
=> Minor fix for assert normalized quaternion

src/generic-transformation/helper.hh, tests/solver-by-substitution.cc
Normalization check was wrong for GenericTransformation that provided as
output a member of SO3.
In tests/solver-by-substitution.cc, random configurations where generated
using setRandom method that does not take into account quaternion
normalization.
This should fix https://github.com/humanoid-path-planner/hpp-constraints/issues/174.
=> Fix wrong asserts and tests.

include/hpp/constraints/solver/hierarchical-iterative.hh, src/solver/hierarchical-iterative.cc
saturation vector is of same size as velocity. Therefore, we need to use
a mapping from configuration indices to velocity indices.
A constructor taking such an object has been added. For backward
compatibility, the default constructor builds a trivial mapping.
=> [HierarchicalIterative] Fix staturation::Bounds computation.

include/hpp/constraints/matrix-view.hh, tests/matrix-view.cc
In Debug mode, in method `Eigen::internal::variable_if_dynamic<T, Value>::setValue`, if `Value` is not `Dynamic` there is a check that the input argument is equal to the `Value` template parameter. This check failed in the tests compiled in debug mode.
This modification fixes the issue.
=> [MatrixView] Fix assert in Eigen

CMakeLists.txt
for installed versions of JRL-cmakemodules
=> CMake: fix find-external path

include/hpp/constraints/explicit.hh, include/hpp/constraints/solver/impl/by-substitution.hh, src/explicit-constraint-set.cc, tests/solver-by-substitution.cc
of the input space.
When an explicit constraint is evaluated out of the definition subspace, it
returns a vector of Nan as the output value.
The solver BySubstitution fails in this case.
=> [Explicit] Explicit constraints may be defined over a subspace
